### ISSUE TITLE
[Feature Request]: [CSS] support reference assets via `url`

### ISSUE THREAD

**Issue by hyf0** [rolldown/rolldown#2921]
### What problem does this feature solve?

Like title said.

### What does the proposed API look like?

Usage exmaple

```css
    @font-face {
        font-family: 'Libre Baskerville';
        font-style: normal;
        font-weight: 400;
        font-display: swap;
        src: url('../assets/libre-baskerville.woff2') format('woff2'),
            local('serif');
    }
```
